apiVersion: apps/v1
kind: Deployment
metadata:
  name: coldchain-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coldchain-api
  template:
    metadata:
      labels:
        app: coldchain-api
    spec:
      containers:
        - name: coldchain-api
          image: <your-ecr-repository>:v1.0.0
          imagePullPolicy: Always
          
          ports:
            - containerPort: 8000

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10

          readinessProbe:
            httpGet:
               path: /health
               port: 8000
            initialDelaySeconds: 10
            periodSeconds: 5

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

