apiVersion: v1
kind: Service
metadata:
  name: coldchain-api-service
spec:
  type: NodePort
  selector:
    app: coldchain-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080